/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as IndiaRouteImport } from './routes/india'
import { Route as CybersecurityRouteImport } from './routes/cybersecurity'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BreakingRouteImport } from './routes/breaking'
import { Route as IndexRouteImport } from './routes/index'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiaRoute = IndiaRouteImport.update({
  id: '/india',
  path: '/india',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityRoute = CybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakingRoute = BreakingRouteImport.update({
  id: '/breaking',
  path: '/breaking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breaking': typeof BreakingRoute
  '/business': typeof BusinessRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/india': typeof IndiaRoute
  '/markets': typeof MarketsRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/science': typeof ScienceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
  '/technology': typeof TechnologyRoute
  '/vehicles': typeof VehiclesRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breaking': typeof BreakingRoute
  '/business': typeof BusinessRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/india': typeof IndiaRoute
  '/markets': typeof MarketsRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/science': typeof ScienceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
  '/technology': typeof TechnologyRoute
  '/vehicles': typeof VehiclesRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breaking': typeof BreakingRoute
  '/business': typeof BusinessRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/india': typeof IndiaRoute
  '/markets': typeof MarketsRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/science': typeof ScienceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
  '/technology': typeof TechnologyRoute
  '/vehicles': typeof VehiclesRoute
  '/world': typeof WorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breaking'
    | '/business'
    | '/cybersecurity'
    | '/india'
    | '/markets'
    | '/notifications'
    | '/saved'
    | '/science'
    | '/search'
    | '/settings'
    | '/sports'
    | '/technology'
    | '/vehicles'
    | '/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breaking'
    | '/business'
    | '/cybersecurity'
    | '/india'
    | '/markets'
    | '/notifications'
    | '/saved'
    | '/science'
    | '/search'
    | '/settings'
    | '/sports'
    | '/technology'
    | '/vehicles'
    | '/world'
  id:
    | '__root__'
    | '/'
    | '/breaking'
    | '/business'
    | '/cybersecurity'
    | '/india'
    | '/markets'
    | '/notifications'
    | '/saved'
    | '/science'
    | '/search'
    | '/settings'
    | '/sports'
    | '/technology'
    | '/vehicles'
    | '/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreakingRoute: typeof BreakingRoute
  BusinessRoute: typeof BusinessRoute
  CybersecurityRoute: typeof CybersecurityRoute
  IndiaRoute: typeof IndiaRoute
  MarketsRoute: typeof MarketsRoute
  NotificationsRoute: typeof NotificationsRoute
  SavedRoute: typeof SavedRoute
  ScienceRoute: typeof ScienceRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SportsRoute: typeof SportsRoute
  TechnologyRoute: typeof TechnologyRoute
  VehiclesRoute: typeof VehiclesRoute
  WorldRoute: typeof WorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india': {
      id: '/india'
      path: '/india'
      fullPath: '/india'
      preLoaderRoute: typeof IndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity': {
      id: '/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/cybersecurity'
      preLoaderRoute: typeof CybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaking': {
      id: '/breaking'
      path: '/breaking'
      fullPath: '/breaking'
      preLoaderRoute: typeof BreakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreakingRoute: BreakingRoute,
  BusinessRoute: BusinessRoute,
  CybersecurityRoute: CybersecurityRoute,
  IndiaRoute: IndiaRoute,
  MarketsRoute: MarketsRoute,
  NotificationsRoute: NotificationsRoute,
  SavedRoute: SavedRoute,
  ScienceRoute: ScienceRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SportsRoute: SportsRoute,
  TechnologyRoute: TechnologyRoute,
  VehiclesRoute: VehiclesRoute,
  WorldRoute: WorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
